# Generated by Django 2.1.7 on 2019-04-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_comments_keyword_categories_keyword_master_profiles_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_categories',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_categories',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_categories',
            name='system',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='default_weight',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='keyword_category_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='system',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='queries',
            name='override',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queries',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='queries',
            name='public',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='queries',
            name='system',
            field=models.IntegerField(default=1),
        ),
    ]
