# Generated by Django 2.1.7 on 2019-04-14 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190414_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_run_id', models.IntegerField()),
                ('user_id', models.IntegerField(default=1)),
                ('query_id', models.IntegerField()),
                ('query_text', models.TextField()),
                ('query_runtime', models.DateTimeField(default=datetime.datetime(2019, 4, 14, 14, 48, 0, 694441), verbose_name='Query Runtime')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField(verbose_name='Rank Result ID')),
                ('query_run_id', models.IntegerField(verbose_name='Query Run')),
                ('article_id', models.IntegerField(verbose_name='Article/Tweet')),
                ('rank_score', models.FloatField(verbose_name='Weighted Score')),
                ('core_score', models.FloatField(verbose_name='Core Score(BM25 Native)')),
                ('ranking', models.FloatField(verbose_name='Ranking')),
                ('source', models.IntegerField(verbose_name='Source')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('tweet_id', models.BigIntegerField(verbose_name='Tweet Id')),
                ('article_text', models.TextField(verbose_name='Original Title/Tweet')),
                ('comments_raw', models.TextField(verbose_name='Comments/Replies')),
            ],
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='default_weight',
            field=models.FloatField(default=100, verbose_name='Default Weight'),
        ),
        migrations.AlterField(
            model_name='keyword_master',
            name='keyword_category_id',
            field=models.IntegerField(default=1, verbose_name='Keyword Category'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='source_id',
            field=models.IntegerField(verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 14, 48, 0, 692441), verbose_name='date published'),
        ),
    ]
