# Generated by Django 2.1.7 on 2019-04-15 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190414_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword_categories',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='keyword_categories',
            name='public',
        ),
        migrations.RemoveField(
            model_name='keyword_categories',
            name='system',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='public',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='system',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='public',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='system',
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 9, 17, 38, 777453), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 9, 17, 38, 775453), verbose_name='date published'),
        ),
    ]
