# Generated by Django 2.1.7 on 2019-04-15 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190415_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='public',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='article_id',
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 4, 19, 146988), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 4, 19, 144987), verbose_name='date published'),
        ),
    ]
