# Generated by Django 2.1.7 on 2019-04-15 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190415_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_id2',
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 19, 51, 878752), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 19, 51, 876754), verbose_name='date published'),
        ),
    ]
