# Generated by Django 2.1.7 on 2019-04-15 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190415_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='source_type_id',
        ),
        migrations.RemoveField(
            model_name='keyword_categories',
            name='keyword_category_id',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='keyword_category_id',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='keyword_id',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='query_id',
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 24, 53, 607937), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 24, 53, 606937), verbose_name='date published'),
        ),
    ]
