# Generated by Django 2.1.7 on 2019-04-15 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190415_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='hashtags',
            name='hashtag_id',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='query_runs',
            name='query_id',
        ),
        migrations.RemoveField(
            model_name='query_runs',
            name='query_run_id',
        ),
        migrations.RemoveField(
            model_name='query_runs',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='query_run_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='tweet_id',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='tweet_id',
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 26, 35, 336432), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 11, 26, 35, 334432), verbose_name='date published'),
        ),
    ]
