# Generated by Django 2.1.7 on 2019-04-15 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190415_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type_id', models.IntegerField()),
                ('source_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Source Id')),
                ('description', models.CharField(max_length=200)),
                ('top_uri', models.CharField(max_length=200)),
                ('source_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Source_Types', verbose_name='Source Types')),
            ],
        ),
        migrations.RemoveField(
            model_name='keyword_categories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='keyword_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='id',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='articles',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Profiles', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='keyword_categories',
            name='keyword_category_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Keyword Category ID'),
        ),
        migrations.AddField(
            model_name='keyword_master',
            name='keyword_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Keyword_Categories'),
        ),
        migrations.AddField(
            model_name='keyword_master',
            name='keyword_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Keyword Id'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='profile_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Profile Id'),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 5, 10, 855643), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 5, 10, 853643), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='articles',
            name='source_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Sources', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='articles',
            name='source_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Source_Types', verbose_name='Source Type'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='source_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Sources', verbose_name='Source'),
        ),
    ]
