# Generated by Django 2.1.7 on 2019-04-15 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190415_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtags',
            name='id',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='id',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='id',
        ),
        migrations.AddField(
            model_name='comments',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Profiles', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='hashtags',
            name='hashtag_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Hashtag ID'),
        ),
        migrations.AddField(
            model_name='queries',
            name='query_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Query ID'),
        ),
        migrations.AddField(
            model_name='query_runs',
            name='query_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Queries', verbose_name='Query'),
        ),
        migrations.AddField(
            model_name='query_runs',
            name='query_run_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rank',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Articles', verbose_name='Article Id'),
        ),
        migrations.AddField(
            model_name='rank',
            name='query_run_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Query_Runs', verbose_name='Query Run Id'),
        ),
        migrations.AddField(
            model_name='rank',
            name='result_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Rank Id'),
        ),
        migrations.AddField(
            model_name='rank',
            name='tweet_id',
            field=models.BigIntegerField(default=1, verbose_name='Tweet Id'),
        ),
        migrations.AddField(
            model_name='replies',
            name='reply_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False, verbose_name='Reply ID (System)'),
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False, verbose_name='Tweet ID (System)'),
        ),
        migrations.AlterField(
            model_name='hashtags',
            name='hashtag_string',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 22, 45, 240241), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='source',
            field=models.IntegerField(default=1, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 22, 45, 237242), verbose_name='date published'),
        ),
    ]
