# Generated by Django 2.1.7 on 2019-04-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190415_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 39, 4, 40594), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 39, 4, 37593), verbose_name='date published'),
        ),
    ]
