# Generated by Django 2.1.7 on 2019-04-15 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190415_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_master',
            name='keyword_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Keyword Id'),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 52, 40, 401919), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 52, 40, 398919), verbose_name='date published'),
        ),
    ]
