# Generated by Django 2.1.7 on 2019-04-15 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190415_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='hashtag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hashtags'),
        ),
        migrations.AddField(
            model_name='tweets',
            name='hashtag_text',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 59, 24, 558428), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 59, 24, 556427), verbose_name='date published'),
        ),
    ]
