# Generated by Django 2.1.7 on 2019-04-15 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190415_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_Imports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.IntegerField()),
                ('run_time', models.DateTimeField(default=datetime.datetime(2019, 4, 15, 15, 6, 26, 472829), verbose_name='Run Time')),
                ('history_time', models.IntegerField(default=24, verbose_name='Lookback period')),
                ('hashtag_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hashtags')),
            ],
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 15, 6, 26, 471829), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 15, 6, 26, 468828), verbose_name='date published'),
        ),
    ]
