# Generated by Django 2.1.7 on 2019-04-21 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190415_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 14, 27, 34, 344048), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='article_text',
            field=models.TextField(blank=True, null=True, verbose_name='Original Title/Tweet'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='comments_raw',
            field=models.TextField(blank=True, null=True, verbose_name='Comments/Replies'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='core_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Core Score(BM25 Native)'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Weighted Score'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='ranking',
            field=models.FloatField(blank=True, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='source',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='tweet_id',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Tweet Id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 14, 27, 34, 341052), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='twitter_imports',
            name='run_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 14, 27, 34, 345048), verbose_name='Run Time'),
        ),
    ]
