# Generated by Django 2.1.7 on 2019-04-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20190421_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rank',
            new_name='Results',
        ),
        migrations.AlterField(
            model_name='query_runs',
            name='query_runtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 6, 9, 10, 872366), verbose_name='Query Runtime'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 6, 9, 10, 870367), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='twitter_imports',
            name='run_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 6, 9, 10, 873367), verbose_name='Run Time'),
        ),
    ]
